import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { spawn } from 'child_process';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const HOOK_EVENTS = [
  'sessionStart',
  'sessionEnd',
  'beforeSubmitPrompt',
  'preToolUse',
  'postToolUse',
  'postToolUseFailure',
  'beforeShellExecution',
  'afterShellExecution',
  'beforeMCPExecution',
  'afterMCPExecution',
  'beforeReadFile',
  'afterFileEdit',
  'preCompact',
  'stop',
  'subagentStart',
  'subagentStop',
  'afterAgentResponse',
  'afterAgentThought',
];

const IS_WIN = process.platform === 'win32';

const HOOKS_DIR     = path.join(os.homedir(), '.cursor', 'hooks');
const HOOKS_JSON    = path.join(os.homedir(), '.cursor', 'hooks.json');
const INSTALLED_PY  = path.join(HOOKS_DIR, 'coralogix_hook.py');
const INSTALLED_ENV = path.join(HOOKS_DIR, 'coralogix_hook.env');
const WRAPPER_SH    = path.join(HOOKS_DIR, 'coralogix_hook.sh');
const WRAPPER_CMD   = path.join(HOOKS_DIR, 'coralogix_hook.cmd');
const WRAPPER_PS1   = path.join(HOOKS_DIR, 'coralogix_hook.ps1');

// hooks.json's registered command — used for install detection, merge, and removal.
const WRAPPER = IS_WIN ? WRAPPER_CMD : WRAPPER_SH;

// ---------------------------------------------------------------------------
// Wrapper scripts
//
// Byte-for-byte the files install.sh / install.ps1 generate, apart from the
// "generated by" line: all three install paths must leave the same hooks
// directory behind. Both wrappers locate their own directory rather than
// embedding absolute paths, and both fall back to exiting quietly, because a
// hook must never break the Cursor session.
// ---------------------------------------------------------------------------

const WRAPPER_SH_CONTENT = `#!/usr/bin/env bash
# Auto-generated by the cursor-coralogix extension — do not edit manually
HOOK_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$HOOK_DIR/coralogix_hook.env"

# Allowlist: the env file only ever holds these keys; refusing anything else
# closes off a PYTHONPATH-style injection surface if it is ever tampered with.
if [[ -f "$ENV_FILE" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    case "$line" in
      CX_API_KEY=*|CX_OTLP_ENDPOINT=*|CX_APPLICATION_NAME=*|CX_SUBSYSTEM_NAME=*|CURSOR_MASK_PROMPTS=*|CURSOR_OMIT_PRE_TOOL_USE_SPANS=*|CX_OTLP_DEBUG=*)
        export "\${line%%=*}=\${line#*=}"
        ;;
    esac
  done < "$ENV_FILE"
fi

# No interpreter: exit quietly. A hook must never break the Cursor session.
command -v python3 >/dev/null 2>&1 || exit 0

exec python3 "$HOOK_DIR/coralogix_hook.py"
`;

const WRAPPER_PS1_CONTENT = `# Auto-generated by the cursor-coralogix extension - do not edit manually

$ErrorActionPreference = 'SilentlyContinue'

try {
    $envFile = Join-Path $PSScriptRoot 'coralogix_hook.env'
    # Allowlist: the env file only ever holds these; refusing anything else
    # closes off a PYTHONPATH-style injection surface if it's tampered with.
    $allowedKeys = @('CX_API_KEY', 'CX_OTLP_ENDPOINT', 'CX_APPLICATION_NAME', 'CX_SUBSYSTEM_NAME', 'CURSOR_MASK_PROMPTS', 'CURSOR_OMIT_PRE_TOOL_USE_SPANS', 'CX_OTLP_DEBUG')
    if (Test-Path -LiteralPath $envFile) {
        foreach ($line in [System.IO.File]::ReadAllLines($envFile)) {
            $t = $line.Trim()
            if ($t -eq '' -or $t.StartsWith('#')) { continue }
            $idx = $t.IndexOf('=')
            if ($idx -lt 1) { continue }
            $k = $t.Substring(0, $idx).Trim()
            $v = $t.Substring($idx + 1).Trim()
            if ($allowedKeys -notcontains $k) { continue }
            [Environment]::SetEnvironmentVariable($k, $v, 'Process')
        }
    }

    $python = $null
    $pyArgs = @()
    foreach ($candidate in @(@('python'), @('py', '-3'), @('python3'))) {
        if (Get-Command $candidate[0] -ErrorAction SilentlyContinue) {
            $python = $candidate[0]
            if ($candidate.Count -gt 1) { $pyArgs = $candidate[1..($candidate.Count - 1)] }
            break
        }
    }
    # No interpreter: exit quietly. A hook must never break the Cursor session.
    if (-not $python) { exit 0 }

    $hook = Join-Path $PSScriptRoot 'coralogix_hook.py'
    & $python ($pyArgs + @($hook))
    exit $LASTEXITCODE
} catch {
    exit 0
}
`;

// CRLF: cmd.exe is the one consumer here that is not reliably LF-tolerant.
const WRAPPER_CMD_CONTENT =
  '@echo off\r\npowershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0coralogix_hook.ps1" %*\r\n';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function isInstalled(): boolean {
  return fs.existsSync(INSTALLED_PY) && fs.existsSync(WRAPPER);
}

// Same rule as install.sh and install.ps1: anything other than https (or a
// collector on this machine) would put the API key on the wire in cleartext.
// The setting is an enum, but a hand-edited settings.json is not validated.
function isAllowedEndpoint(endpoint: string): boolean {
  return (
    /^https:\/\/\S+$/.test(endpoint) ||
    /^http:\/\/(localhost|127\.0\.0\.1|\[::1\])(:\d+)?(\/|$)/.test(endpoint)
  );
}

async function showSettingsError(message: string): Promise<void> {
  const action = await vscode.window.showErrorMessage(message, 'Open Settings');
  if (action === 'Open Settings') {
    vscode.commands.executeCommand('workbench.action.openSettings', 'cursorCoralogix');
  }
}

function buildEnvContent(apiKey: string, cfg: vscode.WorkspaceConfiguration): string {
  const lines = [
    `CX_API_KEY=${apiKey}`,
    `CX_OTLP_ENDPOINT=${cfg.get<string>('otlpEndpoint', '')}`,
    `CX_APPLICATION_NAME=${cfg.get<string>('applicationName', '')}`,
    `CX_SUBSYSTEM_NAME=${cfg.get<string>('subsystemName', '')}`,
    `CURSOR_MASK_PROMPTS=${cfg.get<boolean>('maskPrompts', true)}`,
    `CURSOR_OMIT_PRE_TOOL_USE_SPANS=${cfg.get<boolean>('omitPreToolUseSpans', false)}`,
    `CX_OTLP_DEBUG=${cfg.get<boolean>('debug', false)}`,
  ];
  return lines.join('\n') + '\n';
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function readHooksJson(): Record<string, unknown> | null {
  try {
    const parsed: unknown = JSON.parse(fs.readFileSync(HOOKS_JSON, 'utf8'));
    return isPlainObject(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

function otherHooks(entries: unknown, wrapperPath: string): Record<string, unknown>[] {
  if (!Array.isArray(entries)) return [];
  return entries.filter(
    (e): e is Record<string, unknown> => isPlainObject(e) && e['command'] !== wrapperPath
  );
}

function mergeHooksJson(wrapperPath: string): void {
  const config = readHooksJson() ?? {};

  if (typeof config['version'] === 'undefined') config['version'] = 1;
  if (!isPlainObject(config['hooks'])) config['hooks'] = {};

  const hooks = config['hooks'] as Record<string, unknown>;
  const entry = { command: wrapperPath, timeout: 10 };

  for (const event of HOOK_EVENTS) {
    // Re-running setup replaces our entry instead of appending a duplicate.
    hooks[event] = [...otherHooks(hooks[event], wrapperPath), entry];
  }

  fs.mkdirSync(path.dirname(HOOKS_JSON), { recursive: true });
  fs.writeFileSync(HOOKS_JSON, JSON.stringify(config, null, 2) + '\n');
}

function removeFromHooksJson(wrapperPath: string): void {
  const config = readHooksJson();
  if (!config || !isPlainObject(config['hooks'])) return;

  const hooks = config['hooks'] as Record<string, unknown>;

  for (const event of Object.keys(hooks)) {
    if (!Array.isArray(hooks[event])) continue;
    const remaining = otherHooks(hooks[event], wrapperPath);
    // Drop the event entirely when we were its only hook, so uninstalling
    // leaves hooks.json as it was rather than littered with empty arrays.
    if (remaining.length > 0) {
      hooks[event] = remaining;
    } else {
      delete hooks[event];
    }
  }

  fs.writeFileSync(HOOKS_JSON, JSON.stringify(config, null, 2) + '\n');
}

function updateStatusBar(bar: vscode.StatusBarItem): void {
  const active = isInstalled();
  bar.text = active ? '$(pulse) CX Telemetry' : '$(circle-slash) CX Telemetry';
  bar.tooltip = active
    ? 'Coralogix hook active — click for status'
    : 'Coralogix hook not installed — click to set up';
  bar.backgroundColor = active
    ? undefined
    : new vscode.ThemeColor('statusBarItem.warningBackground');
}

function installPythonDeps(output: vscode.OutputChannel): Promise<void> {
  return new Promise((resolve, reject) => {
    const packages = ['opentelemetry-sdk', 'opentelemetry-exporter-otlp-proto-http'];

    function runPip(cmd: string, prefixArgs: string[], extraArgs: string[], onFail: () => void): void {
      const args = [...prefixArgs, '-m', 'pip', 'install', '--quiet', '--user', '--no-warn-script-location', ...extraArgs, ...packages];
      const proc = spawn(cmd, args);
      let settled = false;

      proc.stdout.on('data', (d: Buffer) => output.append(d.toString()));
      proc.stderr.on('data', (d: Buffer) => output.append(d.toString()));

      // spawn emits ENOENT via 'error'; fall through to the next interpreter.
      proc.on('error', () => {
        if (settled) return;
        settled = true;
        onFail();
      });

      proc.on('close', (code) => {
        if (settled) return;
        settled = true;
        if (code === 0) {
          output.appendLine('Python dependencies installed.');
          resolve();
        } else {
          onFail();
        }
      });
    }

    if (IS_WIN) {
      // Try python, then py -3, then python3; the first one that spawns is reused.
      const candidates: Array<{ cmd: string; prefixArgs: string[] }> = [
        { cmd: 'python', prefixArgs: [] },
        { cmd: 'py', prefixArgs: ['-3'] },
        { cmd: 'python3', prefixArgs: [] },
      ];

      const tryNext = (i: number): void => {
        if (i >= candidates.length) {
          reject(new Error('No Python interpreter found (tried python, py -3, python3)'));
          return;
        }
        const { cmd, prefixArgs } = candidates[i];
        runPip(cmd, prefixArgs, [], () => tryNext(i + 1));
      };

      tryNext(0);
    } else {
      // First attempt: --user
      // Fallback: --user --break-system-packages (Homebrew Python / PEP 668)
      runPip('python3', [], [], () =>
        runPip('python3', [], ['--break-system-packages'], () =>
          reject(new Error('pip install failed — see Output panel for details'))
        )
      );
    }
  });
}

function restrictWindowsAcl(filePath: string, output: vscode.OutputChannel): Promise<void> {
  // Node's `mode: 0o600` is a no-op on NTFS; the file otherwise inherits folder ACLs.
  return new Promise((resolve) => {
    const psLiteral = filePath.replace(/'/g, "''");
    // icacls with the user's SID: strips inheritance atomically and avoids
    // localized account names; PS 5.1's RemoveAccessRule throws on inherited rules.
    const script = [
      '$sid = [System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value',
      `icacls '${psLiteral}' /inheritance:r /grant:r ('*' + $sid + ':F') | Out-Null`,
      'exit $LASTEXITCODE',
    ].join('; ');

    let settled = false;
    const finish = (): void => {
      if (settled) return;
      settled = true;
      resolve();
    };
    const warn = (): void => {
      output.appendLine(`Warning: could not restrict permissions on ${filePath} — it contains your API key.`);
    };

    try {
      const proc = spawn('powershell', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', script]);
      proc.on('error', () => {
        warn();
        finish();
      });
      proc.on('close', (code) => {
        if (code !== 0) warn();
        finish();
      });
    } catch {
      warn();
      finish();
    }
  });
}

// ---------------------------------------------------------------------------
// Activate
// ---------------------------------------------------------------------------

export function activate(context: vscode.ExtensionContext): void {
  const output = vscode.window.createOutputChannel('Coralogix Telemetry');

  const statusBar = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 100);
  statusBar.command = 'cursorCoralogix.status';
  updateStatusBar(statusBar);
  statusBar.show();

  context.subscriptions.push(statusBar, output);

  const SECRET_KEY = 'cursorCoralogix.apiKey';

  // --- Setup command ---
  context.subscriptions.push(
    vscode.commands.registerCommand('cursorCoralogix.setup', async () => {
      const cfg = vscode.workspace.getConfiguration('cursorCoralogix');
      const endpoint = cfg.get<string>('otlpEndpoint', '');
      const applicationName = cfg.get<string>('applicationName', '');
      const subsystemName = cfg.get<string>('subsystemName', '');

      // Retrieve stored key or prompt the user (masked input)
      let apiKey = await context.secrets.get(SECRET_KEY) ?? '';
      if (!apiKey) {
        const input = await vscode.window.showInputBox({
          title: 'Coralogix API Key',
          prompt: 'Paste your Send-Your-Data API key (Settings → API Keys in your tenant)',
          password: true,
          ignoreFocusOut: true,
        });
        if (!input) return;
        await context.secrets.store(SECRET_KEY, input);
        apiKey = input;
      }

      if (!endpoint) {
        await showSettingsError('Set cursorCoralogix.otlpEndpoint in Settings before running setup.');
        return;
      }

      if (!applicationName) {
        await showSettingsError(
          'Set cursorCoralogix.applicationName in Settings before running setup (conventional value: cursor).'
        );
        return;
      }

      if (!subsystemName) {
        await showSettingsError(
          'Set cursorCoralogix.subsystemName in Settings before running setup (conventional value: cursor-sessions).'
        );
        return;
      }

      if (!isAllowedEndpoint(endpoint)) {
        await showSettingsError(
          `Invalid cursorCoralogix.otlpEndpoint: ${endpoint} — it must start with https:// ` +
            '(or http://localhost, http://127.0.0.1, http://[::1] for a local collector) and contain no spaces.'
        );
        return;
      }

      output.show(true);
      output.appendLine('--- Coralogix hook setup ---');

      try {
        // 1. Create hooks directory
        fs.mkdirSync(HOOKS_DIR, { recursive: true });

        // 2. Write env file (chmod 600 — credentials)
        fs.writeFileSync(INSTALLED_ENV, buildEnvContent(apiKey, cfg), { mode: 0o600 });
        output.appendLine(`Env written:       ${INSTALLED_ENV}`);
        if (IS_WIN) {
          await restrictWindowsAcl(INSTALLED_ENV, output);
        }

        // 3. Copy hook.py from extension resources
        const srcHook = path.join(context.extensionPath, 'resources', 'hook.py');
        fs.copyFileSync(srcHook, INSTALLED_PY);
        output.appendLine(`Hook installed:    ${INSTALLED_PY}`);

        // 4. Write runtime wrapper (kept identical to the one install.ps1 /
        //    install.sh generate, so all three install paths behave the same)
        if (IS_WIN) {
          fs.writeFileSync(WRAPPER_PS1, WRAPPER_PS1_CONTENT);
          output.appendLine(`Wrapper installed: ${WRAPPER_PS1}`);

          fs.writeFileSync(WRAPPER_CMD, WRAPPER_CMD_CONTENT);
          output.appendLine(`Wrapper installed: ${WRAPPER_CMD}`);
        } else {
          fs.writeFileSync(WRAPPER_SH, WRAPPER_SH_CONTENT, { mode: 0o755 });
          output.appendLine(`Wrapper installed: ${WRAPPER_SH}`);
        }

        // 5. Merge hooks.json
        mergeHooksJson(WRAPPER);
        output.appendLine(`Hooks merged into: ${HOOKS_JSON}`);

        // 6. Install Python dependencies
        output.appendLine('Installing Python dependencies...');
        await installPythonDeps(output);

        updateStatusBar(statusBar);
        output.appendLine('\nDone! Restart Cursor to activate telemetry.');
        vscode.window.showInformationMessage(
          'Coralogix hooks installed. Restart Cursor to activate.',
          'Open Output'
        ).then((action) => {
          if (action === 'Open Output') output.show();
        });
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        output.appendLine(`\nSetup failed: ${msg}`);
        vscode.window.showErrorMessage(`Coralogix setup failed: ${msg}`);
      }
    })
  );

  // --- Set API Key command ---
  context.subscriptions.push(
    vscode.commands.registerCommand('cursorCoralogix.setApiKey', async () => {
      const input = await vscode.window.showInputBox({
        title: 'Coralogix API Key',
        prompt: 'Paste your Send-Your-Data API key (Settings → API Keys in your tenant)',
        password: true,
        ignoreFocusOut: true,
      });
      if (!input) return;
      await context.secrets.store(SECRET_KEY, input);
      vscode.window.showInformationMessage('Coralogix API key saved. Run setup to apply.');
    })
  );

  // --- Uninstall command ---
  context.subscriptions.push(
    vscode.commands.registerCommand('cursorCoralogix.uninstall', async () => {
      const confirm = await vscode.window.showWarningMessage(
        'Remove Coralogix hooks from Cursor?',
        { modal: true },
        'Remove'
      );
      if (confirm !== 'Remove') return;

      try {
        removeFromHooksJson(WRAPPER);
        const filesToRemove = IS_WIN
          ? [INSTALLED_PY, INSTALLED_ENV, WRAPPER_CMD, WRAPPER_PS1]
          : [INSTALLED_PY, INSTALLED_ENV, WRAPPER_SH];
        for (const f of filesToRemove) {
          try { fs.unlinkSync(f); } catch { /* already gone */ }
        }
        await context.secrets.delete(SECRET_KEY);
        updateStatusBar(statusBar);
        output.appendLine('Coralogix hooks removed.');
        output.appendLine(
          `Cached conversation state remains in ${path.join(os.homedir(), '.cursor-hook-state')} (safe to delete).`
        );
        vscode.window.showInformationMessage(
          'Coralogix hooks removed. Restart Cursor to deactivate.'
        );
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        vscode.window.showErrorMessage(`Uninstall failed: ${msg}`);
      }
    })
  );

  // --- Status command ---
  context.subscriptions.push(
    vscode.commands.registerCommand('cursorCoralogix.status', () => {
      output.show();
      output.appendLine('\n--- Coralogix status ---');
      output.appendLine(`Hook active:  ${isInstalled()}`);
      output.appendLine(`Python hook:  ${INSTALLED_PY}  [${fs.existsSync(INSTALLED_PY) ? 'present' : 'missing'}]`);
      output.appendLine(`Env file:     ${INSTALLED_ENV}  [${fs.existsSync(INSTALLED_ENV) ? 'present' : 'missing'}]`);
      output.appendLine(`Wrapper:      ${WRAPPER}  [${fs.existsSync(WRAPPER) ? 'present' : 'missing'}]`);
      if (IS_WIN) {
        output.appendLine(`  PS1 script: ${WRAPPER_PS1}  [${fs.existsSync(WRAPPER_PS1) ? 'present' : 'missing'}]`);
      }
      output.appendLine(`hooks.json:   ${HOOKS_JSON}  [${fs.existsSync(HOOKS_JSON) ? 'present' : 'missing'}]`);
    })
  );
}

export function deactivate(): void {}
